version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=9898  # Устанавливаем пароль для Redis
    ports:
      - "6380:6379"  # Пробрасываем порт
    volumes:
      - ./redisdata:/data  # Том для данных
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "9898", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: redis-server --requirepass 9898  # Указываем пароль в командной строке Redis
