"""create file

Revision ID: ba3a0455e77d
Revises: 7063ab81c581
Create Date: 2025-03-29 15:09:22.845289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3a0455e77d'
down_revision: Union[str, None] = '7063ab81c581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('photo', sa.String(length=255), nullable=True))
    op.add_column('post', sa.Column('media', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('post', 'media')
    op.drop_column('channels', 'photo')
    # ### end Alembic commands ###
